# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopifyThemeManager < Formula
  desc "Shopify Theme Manager CLI"
  homepage "https://github.com/colinxr/shopify-theme-manager"
  version "0.0.7-j"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-j/shopify-theme-manager_Darwin_x86_64.tar.gz"
      sha256 "f2aeed87056a59eb2b0056a7d9f9fbc7335919080b8c4744575743ceeb9f568e"

      def install
        bin.install "stm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-j/shopify-theme-manager_Darwin_arm64.tar.gz"
      sha256 "5628beef4825fa6e5a47c083c1f1d600a9f147e1186933250fa85f845cbb9db5"

      def install
        bin.install "stm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-j/shopify-theme-manager_Linux_x86_64.tar.gz"
        sha256 "f155875333af54f4931f10deb87749a1b1500f42eeb59abda84b46dec7175a20"

        def install
          bin.install "stm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-j/shopify-theme-manager_Linux_arm64.tar.gz"
        sha256 "900016980dbd4e1342c67df989782b5a13a327382bca6dbb97183e2025744265"

        def install
          bin.install "stm"
        end
      end
    end
  end

  test do
    system "#{bin}/stm --version"
  end
end
