# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopifyThemeManager < Formula
  desc "Shopify Theme Manager CLI"
  homepage "https://github.com/colinxr/shopify-theme-manager"
  version "0.0.8-k"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.8-k/shopify-theme-manager_Darwin_x86_64.tar.gz"
      sha256 "dd9cfd9c0f2e7ec5c1753f908941fc452ea9f62b5cec4904f03ee641a85ddf11"

      def install
        bin.install "stm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.8-k/shopify-theme-manager_Darwin_arm64.tar.gz"
      sha256 "574826c3878cf23f0fa27e6f497fce5c882cd6faff8b05b765ac0b8a0e2ad1e5"

      def install
        bin.install "stm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.8-k/shopify-theme-manager_Linux_x86_64.tar.gz"
        sha256 "69fff4a1ce0a4146b10b8c0b8478d1af18d65f828b1f9622aa5b0c45076b9c9b"

        def install
          bin.install "stm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.8-k/shopify-theme-manager_Linux_arm64.tar.gz"
        sha256 "234dba5fa8549d90e6e7ffb3631342ee77228db5ab126eacb0bafde4f5f4cc6c"

        def install
          bin.install "stm"
        end
      end
    end
  end

  test do
    system "#{bin}/stm --version"
  end
end
