# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShopifyThemeManager < Formula
  desc "Shopify Theme Manager CLI"
  homepage "https://github.com/colinxr/shopify-theme-manager"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.9/shopify-theme-manager_Darwin_x86_64.tar.gz"
      sha256 "b3ca360b629ee330d49688a405e6acc8e0bf5d953b84ae9eec457a27dc541098"

      def install
        bin.install "stm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.9/shopify-theme-manager_Darwin_arm64.tar.gz"
      sha256 "1910f9e5c40faa2b60098e2c61a98704891dcf077bf76096c7ade40ca9eea00e"

      def install
        bin.install "stm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.9/shopify-theme-manager_Linux_x86_64.tar.gz"
        sha256 "c1439ef02203736562b98802ee4c80bbcb05a716b11478e8669efe6f75add8c5"

        def install
          bin.install "stm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.9/shopify-theme-manager_Linux_arm64.tar.gz"
        sha256 "4d2f130e093fc35fd4767c7575dbceb74fdf500d27f67b8b59bbd8bfe38a8fee"

        def install
          bin.install "stm"
        end
      end
    end
  end

  test do
    system "#{bin}/stm --version"
  end
end
