# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stm < Formula
  desc "Shopify Theme Manager CLI"
  homepage "https://github.com/colinxr/shopify-theme-manager"
  version "0.0.7-g"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-g/shopify-theme-manager_Darwin_x86_64.tar.gz"
      sha256 "62886182a2f8c062b8c7d07922576366c2947395d164d8b047b927b4451f5ac9"

      def install
        bin.install "stm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-g/shopify-theme-manager_Darwin_arm64.tar.gz"
      sha256 "fa53ff3219fa82608792cad6ff66169513bf986b09cbbc34e55a1bb2203787cd"

      def install
        bin.install "stm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-g/shopify-theme-manager_Linux_x86_64.tar.gz"
        sha256 "d486db93cb327f9542d80a1dd1125c478e0b1600c620d3bb75b3ddb81303a1a0"

        def install
          bin.install "stm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/colinxr/shopify-theme-manager/releases/download/v0.0.7-g/shopify-theme-manager_Linux_arm64.tar.gz"
        sha256 "215c3d9d8b1926d72e8295252ad67149e2acb65b4af90d106bba425c2ad98777"

        def install
          bin.install "stm"
        end
      end
    end
  end

  test do
    system "#{bin}/stm --version"
  end
end
